# Generated by Django 3.2.9 on 2021-11-21 23:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('adult', models.BooleanField()),
                ('popularity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('poster_path', models.TextField()),
                ('release_date', models.TextField()),
                ('runtime', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vote_average', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('vote_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('overview', models.TextField()),
                ('original_title', models.TextField()),
                ('genres', models.ManyToManyField(to='movies.Genre')),
                ('like_users', models.ManyToManyField(related_name='like_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
