# Generated by Django 3.2.9 on 2021-11-25 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_worldcup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worldcup',
        ),
    ]
